name: Executar Pipeline
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar tratamento de dados
        run: python scripts/desafio_1.py

      - name: Executar clusterização e regras simples
        run: python scripts/desafio_2.py

      - name: Executar previsão do próximo trecho
        run: python scripts/desafio_3.py

      - name: Upload dos resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultados-pipeline
          path: dados/resultados/